Repository koongFan/todayCody, pull requests merged in 2023-07, with the labels that each got.

#54 chore & feat: 로그인 후 넷바에 닉네임 표시 및 마이페이지 정보 받아옴
  todayCody/frontend/config-overrides.js
  todayCody/frontend/package-lock.json
  todayCody/frontend/package.json
  todayCody/frontend/src/App.js
  todayCody/frontend/src/api/auth.js
  todayCody/frontend/src/components/layout/Header.jsx
  todayCody/frontend/src/components/layout/Sidebar.jsx
  todayCody/frontend/src/contexts/AuthContext.jsx
  todayCody/frontend/src/pages/MyPage.jsx
  todayCody/frontend/src/pages/RootLayout.jsx
  todayCody/frontend/src/util/auth.js
Labels: feat

#56 feat: 마이페이지 라우트 보호
  todayCody/frontend/src/App.js
  todayCody/frontend/src/components/layout/Header.jsx
Labels: feat

#58 style & refactor: 피드 업로드 스타일링 및 업로드 로직 리팩토링
  todayCody/frontend/.gitignore
  todayCody/frontend/public/icons/add.png
  todayCody/frontend/public/icons/check.svg
  todayCody/frontend/public/icons/photo.png
  todayCody/frontend/src/App.js
  todayCody/frontend/src/api/auth.js
  todayCody/frontend/src/pages/MyPage.jsx
  todayCody/frontend/src/pages/NewPost.jsx
  todayCody/frontend/src/scss/_reset.scss
  todayCody/frontend/src/scss/main.scss
  todayCody/frontend/src/scss/pages/_mypage.scss
  todayCody/frontend/src/scss/pages/_newpost.scss
Labels: style, refactor

#59 style & bug : 로그인, 게시물 목록 페이지 스타일링
  todayCody/frontend/public/icons/logo-small.png
  todayCody/frontend/public/icons/mail.svg
  todayCody/frontend/public/icons/write.svg
  todayCody/frontend/src/components/board/BoardList.jsx
  todayCody/frontend/src/pages/Board.jsx
  todayCody/frontend/src/pages/SignIn.jsx
  todayCody/frontend/src/scss/pages/_board.scss
  todayCody/frontend/src/scss/pages/_signin.scss
Labels: bug, style

#60 style: 게시물 상세보기 페이지 스타일링
  todayCody/frontend/public/icons/.svg
  todayCody/frontend/public/icons/avatar.png
  todayCody/frontend/public/icons/report.svg
  todayCody/frontend/public/icons/thumb.svg
  todayCody/frontend/src/components/board/BoardPost.jsx
  todayCody/frontend/src/scss/main.scss
  todayCody/frontend/src/scss/pages/_postDetail.scss
Labels: 🎨 style

#64 style : Figma Design Token 초기 등록 및 적용
  todayCody/frontend/design/tokens.json
Labels: 🎨 style
